version: "3.4"
services:
  node_app_test:
    image: node-app:test
    build: 
      context: .
      dockerfile: test.dockerfile
      args:
        CI: 'true'
  node_app:
    image: node-app:prod
    depends_on: 
      - node_app_test
    build: 
      context: .
      dockerfile: dockerfile
      args:
        CI: 'false'
    ports:
        - 3000:3000
